### ISSUE TITLE
Move Icon Browser into this repo

### ISSUE THREAD

**Issue by pyrello** [uiowa/brand-icons#33]
# Motivation

I don't remember why we decided that two repos was a good idea for icons + icon browser, but it is a maintenance PITA! To make any changes to the icons repo, we have to update the other repo to accommodate those changes.

# Proposed solution

Build the icon browser into this repo and archive https://github.com/uiowa/brand-icon-browser

**Comment by quamsta** [comment]
@pyrello The original intent behind two repos was to eventually make this repo serve as either an API-like endpoint for the Icon Browser or have it be otherwise consumable (or even editable) by other utilities without having to rebuild the entire Icon Browser web application. It was my attempt at separation of concerns (data vs application).

This, in theory, meant that changes, additions, etc. to the icon set wouldn't require a new version or release of the browser itself-- the browser would just automatically be consuming the updated set, along with anything else that was consuming it. 

In practice, it was a PITA, even while working on it. It was something I wanted to work on improving and/or merging at some point.

**Comment by quamsta** [comment]
As an example, this is how FontAwesome does this:

- Main icon repo, which contains icons, needed stylesheets, etc : https://github.com/FortAwesome/Font-Awesome (in [js-packages/@fortawesome](https://github.com/FortAwesome/Font-Awesome/tree/6.x/js-packages/%40fortawesome)

Which is consumed by:

- https://github.com/FortAwesome/vue-fontawesome
- https://github.com/FortAwesome/react-fontawesome/

etc.
